import { useEffect, useState } from "react";
import { tenderlensApi } from "../api/tenderlens.js";
import Icon from "../components/Icons.jsx";
import StatCard from "../components/StatCard.jsx";

export default function Report({ tenderId, selectedTender, notify }) {
  const [summary, setSummary] = useState(null);
  const [latestReport, setLatestReport] = useState(null);
  const [generatedBy, setGeneratedBy] = useState("OFFICER");
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    if (!tenderId) return;
    tenderlensApi.evaluationSummary(tenderId).then(setSummary).catch((error) => notify(error.message));
  }, [tenderId, notify]);

  async function generate() {
    setBusy(true);
    try {
      const report = await tenderlensApi.generateReport(tenderId, generatedBy);
      setLatestReport(report);
      notify(report.message || "Report generated.");
    } catch (error) {
      notify(error.message);
    } finally {
      setBusy(false);
    }
  }

  const totals = (summary?.summaries || []).reduce(
    (acc, bidder) => {
      acc[bidder.overallVerdict] = (acc[bidder.overallVerdict] || 0) + 1;
      return acc;
    },
    {}
  );

  return (
    <div className="report-page">
      <section className="stat-grid">
        <StatCard icon="upload" label="Total bidders" value={summary?.totalBidders || 0} tone="blue" />
        <StatCard icon="matrix" label="Eligible" value={totals.ELIGIBLE || latestReport?.eligibleCount || 0} tone="green" />
        <StatCard icon="review" label="Needs review" value={totals.NEEDS_REVIEW || latestReport?.needsReviewCount || 0} tone="yellow" />
        <StatCard icon="audit" label="Not eligible" value={totals.NOT_ELIGIBLE || latestReport?.notEligibleCount || 0} tone="red" />
      </section>

      <section className="panel wide">
        <div className="section-title">
          <div>
            <span className="eyebrow">{selectedTender?.tenderRef}</span>
            <h2>PDF report</h2>
          </div>
          <div className="confirm-strip">
            <input value={generatedBy} onChange={(e) => setGeneratedBy(e.target.value)} aria-label="Generated by" />
            <button className="button primary" type="button" disabled={busy} onClick={generate}>
              <Icon name="report" /> {busy ? "Generating..." : "Generate report"}
            </button>
            <a className="button" href={tenderlensApi.reportDownloadUrl(tenderId)}>
              <Icon name="download" /> Download PDF
            </a>
          </div>
        </div>

        {selectedTender?.status === "UPLOADED" || selectedTender?.status === "CRITERIA_EXTRACTED" ? (
          <div className="warning-box">
            Reports can be generated after criteria are confirmed and evaluation has produced bidder verdicts.
          </div>
        ) : null}

        <div className="meta-grid">
          <div><span>Latest file</span><strong>{latestReport?.fileName || "Generate a report to see metadata"}</strong></div>
          <div><span>Generated at</span><strong>{latestReport?.generatedAt ? new Date(latestReport.generatedAt).toLocaleString() : "-"}</strong></div>
          <div><span>Report ID</span><strong>{latestReport?.reportId || "-"}</strong></div>
          <div><span>Backend endpoint</span><strong>/report/download</strong></div>
        </div>
      </section>

      <section className="panel wide">
        <div className="section-title">
          <div>
            <span className="eyebrow">History</span>
            <h2>Previous reports</h2>
          </div>
        </div>
        <div className="empty-state small">
          The backend exposes latest report download and generation metadata. A full report-history endpoint is not present yet.
        </div>
      </section>
    </div>
  );
}
